name: Push
run-name: ${{github.actor}} is learning Github Actions
on: {push}
jobs: 
  check-bats-version:
    name: Build
    runs-on: ubuntu-lastest
    steps:
      - users: actions/checkout@v3
      - users: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g bats
      - run: bats -v